<?php

namespace DoctrineProxies\__CG__\Shlinkio\Shlink\Core\Visit\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Visit extends \Shlinkio\Shlink\Core\Visit\Entity\Visit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'potentialBot' => [parent::class, 'potentialBot', null],
        "\0".parent::class."\0".'referer' => [parent::class, 'referer', null],
        "\0".parent::class."\0".'remoteAddr' => [parent::class, 'remoteAddr', null],
        "\0".parent::class."\0".'shortUrl' => [parent::class, 'shortUrl', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'userAgent' => [parent::class, 'userAgent', null],
        "\0".parent::class."\0".'visitLocation' => [parent::class, 'visitLocation', null],
        "\0".parent::class."\0".'visitedUrl' => [parent::class, 'visitedUrl', null],
        'date' => [parent::class, 'date', null],
        'id' => [parent::class, 'id', null],
        'potentialBot' => [parent::class, 'potentialBot', null],
        'referer' => [parent::class, 'referer', null],
        'remoteAddr' => [parent::class, 'remoteAddr', null],
        'shortUrl' => [parent::class, 'shortUrl', null],
        'type' => [parent::class, 'type', null],
        'userAgent' => [parent::class, 'userAgent', null],
        'visitLocation' => [parent::class, 'visitLocation', null],
        'visitedUrl' => [parent::class, 'visitedUrl', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
