<?php

namespace DoctrineProxies\__CG__\Shlinkio\Shlink\Core\Visit\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VisitLocation extends \Shlinkio\Shlink\Core\Visit\Entity\VisitLocation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'cityName' => [parent::class, 'cityName', null],
        "\0".parent::class."\0".'countryCode' => [parent::class, 'countryCode', null],
        "\0".parent::class."\0".'countryName' => [parent::class, 'countryName', null],
        "\0".parent::class."\0".'isEmpty' => [parent::class, 'isEmpty', null],
        "\0".parent::class."\0".'latitude' => [parent::class, 'latitude', null],
        "\0".parent::class."\0".'longitude' => [parent::class, 'longitude', null],
        "\0".parent::class."\0".'regionName' => [parent::class, 'regionName', null],
        "\0".parent::class."\0".'timezone' => [parent::class, 'timezone', null],
        'cityName' => [parent::class, 'cityName', null],
        'countryCode' => [parent::class, 'countryCode', null],
        'countryName' => [parent::class, 'countryName', null],
        'id' => [parent::class, 'id', null],
        'isEmpty' => [parent::class, 'isEmpty', null],
        'latitude' => [parent::class, 'latitude', null],
        'longitude' => [parent::class, 'longitude', null],
        'regionName' => [parent::class, 'regionName', null],
        'timezone' => [parent::class, 'timezone', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
