<?php

namespace DoctrineProxies\__CG__\Shlinkio\Shlink\Core\RedirectRule\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RedirectCondition extends \Shlinkio\Shlink\Core\RedirectRule\Entity\RedirectCondition implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'matchKey' => [parent::class, 'matchKey', parent::class],
        "\0".parent::class."\0".'matchValue' => [parent::class, 'matchValue', parent::class],
        "\0".parent::class."\0".'type' => [parent::class, 'type', parent::class],
        'id' => [parent::class, 'id', null],
        'matchKey' => [parent::class, 'matchKey', parent::class],
        'matchValue' => [parent::class, 'matchValue', parent::class],
        'type' => [parent::class, 'type', parent::class],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
