<?php

namespace DoctrineProxies\__CG__\Shlinkio\Shlink\Rest\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ApiKey extends \Shlinkio\Shlink\Rest\Entity\ApiKey implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'enabled' => [parent::class, 'enabled', null],
        "\0".parent::class."\0".'expirationDate' => [parent::class, 'expirationDate', null],
        "\0".parent::class."\0".'key' => [parent::class, 'key', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        'enabled' => [parent::class, 'enabled', null],
        'expirationDate' => [parent::class, 'expirationDate', null],
        'id' => [parent::class, 'id', null],
        'key' => [parent::class, 'key', null],
        'name' => [parent::class, 'name', null],
        'roles' => [parent::class, 'roles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
