<?php

namespace DoctrineProxies\__CG__\Shlinkio\Shlink\Core\Domain\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Domain extends \Shlinkio\Shlink\Core\Domain\Entity\Domain implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'baseUrlRedirect' => [parent::class, 'baseUrlRedirect', null],
        "\0".parent::class."\0".'invalidShortUrlRedirect' => [parent::class, 'invalidShortUrlRedirect', null],
        "\0".parent::class."\0".'regular404Redirect' => [parent::class, 'regular404Redirect', null],
        'authority' => [parent::class, 'authority', parent::class],
        'baseUrlRedirect' => [parent::class, 'baseUrlRedirect', null],
        'id' => [parent::class, 'id', null],
        'invalidShortUrlRedirect' => [parent::class, 'invalidShortUrlRedirect', null],
        'regular404Redirect' => [parent::class, 'regular404Redirect', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
